networks:
  localmailer_network:

services:
  webapp:
    build:
      context: .
      dockerfile: ./apps/webapp/Dockerfile
      args:
        NEXT_PUBLIC_SMTP_HOST: ${NEXT_PUBLIC_SMTP_HOST}
    ports:
      - "${WEBAPP_PORT:-3000}:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - localmailer_network
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d localmailer -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: localmailer
    networks:
      - localmailer_network
