# ---------------------------------
# BASE STAGE
# ---------------------------------
FROM node:lts-alpine AS base

RUN apk update && apk add --no-cache libc6-compat

RUN npm i -g pnpm@11.24.0
# ---------------------------------

# ---------------------------------
# PRUNE STAGE
# ---------------------------------
FROM base AS pruner

RUN apk update

WORKDIR /app

COPY . ./

RUN pnpm dlx turbo prune webapp --docker
# ---------------------------------

# ---------------------------------
# BUILD STAGE
# ---------------------------------
FROM base AS builder

RUN apk update

WORKDIR /app

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./
RUN pnpm i --frozen-lockfile

COPY --from=pruner /app/out/full/ .

WORKDIR /app/apps/webapp
RUN pnpm run prisma:contract:emit
WORKDIR /app

RUN pnpm dlx turbo run build --filter=webapp...
# ---------------------------------

# ---------------------------------
# RUNNER STAGE
# ---------------------------------
FROM builder AS runner

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/apps/webapp/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/apps/webapp/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/webapp/.next/static ./.next/static

WORKDIR /app/apps/webapp

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

CMD ["pnpm", "dlx", "prisma db update"]
# ---------------------------------
