name: WEBAPP CI/CD

on:
  push:
    paths:
      - "apps/webapp/**"
    branches: [dev, main]
  pull_request:
    paths:
      - "apps/webapp/**"
    branches: [dev, main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Enable Corepack & Init Pnpm
        run: |
          npx corepack enable pnpm
          npx corepack prepare pnpm@11.24.0 --activate

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm dlx turbo run webapp#build

      - name: Lint
        run: pnpm dlx turbo run webapp#lint

      - name: Test
        run: pnpm dlx turbo run webapp#test
